parser sometimes threw due to missing "return" statement (#677)
* parser sometimes threw due to missing "return" statement

callstack.
Error: index is out of range
    at TextRangeCollection.getItemAt 
    at Parser._peekToken 
    at Parser._makeExpressionOrTuple 
    at Parser.parseTextExpression 
    at Parser._parseFormatStringSegment 
    at Parser._parseFormatString
    at Parser._parseStringList 
    at Parser._parseAtom 
    at Parser._parseAtomExpression 
    at Parser._parseArithmeticFactor 

* added test coverage